[package]
name = "windows_bindings"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
windows = "0.19"

[dependencies]
windows = "0.19"