name: sanzu release

on:
  push:
    tags:
      - "sanzu-v*"

env:
  GITHUB_REF: "${{ github.ref }}"

jobs:

  docker-alpine:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
      - name: build
        run: cargo clean && cd build && make alpine

      - name: Upload resulting 'alpine bins'
        uses: actions/upload-artifact@v3
        with:
          name: sanzu-alpine-release
          path: |
            ./target/release/sanzu_client
            ./target/release/sanzu_server
            ./target/release/sanzu_proxy
            ./target/release/sanzu_broker


  docker-debian:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
      - name: build
        run: cargo clean && cd build && make debian

      - name: Upload resulting 'debian pkg'
        uses: actions/upload-artifact@v3
        with:
          name: sanzu-debian-release
          path: ./target/debian/sanzu*.deb

  docker-alma8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
      - name: build
        run: cargo clean && cd build && make almalinux8

      - name: Upload resulting 'alma8 pkg'
        uses: actions/upload-artifact@v3
        with:
          name: sanzu-alma8-release
          path: ./target/generate-rpm/sanzu*.rpm

  docker-alma9:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
      - name: build
        run: cargo clean && cd build && make almalinux9

      - name: Upload resulting 'alma9 pkg'
        uses: actions/upload-artifact@v3
        with:
          name: sanzu-alma9-release
          path: ./target/generate-rpm/sanzu*.rpm

  docker-windows:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          components: rustfmt
      - name: build
        run: cargo clean && cd build && make windows

      - name: Upload resulting 'windows pkg'
        uses: actions/upload-artifact@v3
        with:
          name: sanzu-windows-release
          path: ./target/windows/sanzu*.zip

  release:
    # From https://github.com/cloudflare/wrangler/blob/master/.github/workflows/release.yml
    name: GitHub Release
    needs: [docker-alpine, docker-alma8, docker-alma9, docker-debian, docker-windows]
    runs-on: ubuntu-latest
    steps:
      - name: Query version number
        id: get_version
        shell: bash
        run: |
          echo "using version tag ${GITHUB_REF:17}"
          echo ::set-output name=version::"${GITHUB_REF:17}"
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get Changelog Entry
        id: changelog_reader
        uses: mindsers/changelog-reader-action@v2
        with:
          path: ./CHANGELOG.md
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: sanzu-${{ steps.get_version.outputs.VERSION }}
          release_name: sanzu-${{ steps.get_version.outputs.VERSION }}
          body: ${{ steps.changelog_reader.outputs.changes }}
          draft: true

      - name: Download Alpine artifact
        uses: actions/download-artifact@v1
        with:
          name: sanzu-alpine-release

      - name: Download Debian artifact
        uses: actions/download-artifact@v1
        with:
          name: sanzu-debian-release

      - name: Download Alma8 artifact
        uses: actions/download-artifact@v1
        with:
          name: sanzu-alma8-release

      - name: Download Alma9 artifact
        uses: actions/download-artifact@v1
        with:
          name: sanzu-alma9-release

      - name: Download Windows artifact
        uses: actions/download-artifact@v1
        with:
          name: sanzu-windows-release

      - name: compression_alpine
        shell: bash
        run: |
          zip -r sanzu-alpine.zip sanzu-alpine-release

      - name: compression_debian
        shell: bash
        run: |
          zip -r sanzu-debian.zip sanzu-debian-release

      - name: compression_alma8
        shell: bash
        run: |
          zip -r sanzu-alma8.zip sanzu-alma8-release

      - name: compression_alma9
        shell: bash
        run: |
          zip -r sanzu-alma9.zip sanzu-alma9-release

      - name: compression_windows
        shell: bash
        run: |
          zip -r sanzu-windows.zip sanzu-windows-release

      - name: Release Alpine artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./sanzu-alpine.zip
          asset_content_type: application/octet-stream
          asset_name: sanzu-alpine-${{ steps.get_version.outputs.VERSION }}.zip

      - name: Release Debian artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./sanzu-debian.zip
          asset_content_type: application/octet-stream
          asset_name: sanzu-debian-${{ steps.get_version.outputs.VERSION }}.zip

      - name: Release Alma8 artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./sanzu-alma8.zip
          asset_content_type: application/octet-stream
          asset_name: sanzu-alma8-${{ steps.get_version.outputs.VERSION }}.zip

      - name: Release Alma9 artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./sanzu-alma9.zip
          asset_content_type: application/octet-stream
          asset_name: sanzu-alma9-${{ steps.get_version.outputs.VERSION }}.zip

      - name: Release Windows artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./sanzu-windows.zip
          asset_content_type: application/octet-stream
          asset_name: sanzu-windows-${{ steps.get_version.outputs.VERSION }}.zip
